### ISSUE TITLE
dotenv issue

### ISSUE THREAD

**Issue by Rj979** [BenGOsborn/Bulk-OpenSea-Uploader#1]
Loading .env environment variables...
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    import dotenv
ModuleNotFoundError: No module named 'dotenv'

**Comment by BenGOsborn** [comment]
Make sure that you've run `pipenv install` before trying to execute the script, and make sure that you're running the script through pipenv.

If that doesn't work, follow the instructions [here](https://github.com/BenGOsborn/Bulk-OpenSea-Uploader/blob/main/README.md).
